# site details
name: Minidown
description: Minidown is an open-source online publication.
url: https://minidown.github.io/

# social profiles. just remove unneeded profiles.
github: minidown

highlighter: pygments
permalink: /article/:title.html

markdown: redcarpet

exclude: [readme.md]
include: [.htaccess]
