# site details
name: Markdawn
description: Markdawn is an open-source online publication.
url: https://minidawn.github.io/

# social profiles. just remove unneeded profiles.
github: minidawn

highlighter: pygments
permalink: /article/:title.html

markdown: redcarpet

exclude: [readme.md]
include: [.htaccess]
